spring.config.import=optional:file:.env[.properties]
spring.application.name=gymapp
spring.datasource.url=jdbc:postgresql://${PGHOST}/${PGDATABASE}?sslmode=${PGSSLMODE:require}&channelBinding=${PGCHANNELBINDING:require}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

app.jwt.secret=${APP_JWT_SECRET}
app.jwt.expiration-ms=86400000
